update ta jobs to not run on collector release

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -65,9 +65,13 @@ manual_release_trigger:
       if ! echo "$RELEASE_VERSION" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+(-beta\.[0-9]+)?(-rc\.[0-9]+)?$'; then
         echo "RELEASE_VERSION must be in format v1.2.3 for stable releases and in the format v1.2.3-rc.0 or v1.2.3-beta.1 for pre-releases." && exit 1
       fi
-      # Validate version is in changelog
-      if ! grep -q "^## $RELEASE_VERSION" CHANGELOG.md; then
-        echo "Version $RELEASE_VERSION not found in CHANGELOG.md" && exit 1
+      if echo "$RELEASE_VERSION" | grep -Eq '-(beta|rc)\.[0-9]+$'; then
+        echo "Pre-release version detected ($RELEASE_VERSION). Skipping changelog validation."
+      else
+        # Validate version is in changelog only for stable releases
+        if ! grep -q "^## $RELEASE_VERSION" CHANGELOG.md; then
+          echo "Version $RELEASE_VERSION not found in CHANGELOG.md" && exit 1
+        fi
       fi
       echo "Manual release triggered for version $RELEASE_VERSION"
   rules:
@@ -478,6 +482,9 @@ agent-bundle-windows:
       - dist/agent-bundle_windows_amd64.zip
 .collector-ta-trigger:
   rules:
+    # exclude manual collector release
+    - if: $RELEASE_VERSION =~ /^v[0-9]+\.[0-9]+\.[0-9]+.*/
+      when: never
     - <<: *main-condition
     - <<: *no-schedules-condition
     - if: $CI_COMMIT_BRANCH =~ /^release\/technical-addon\/v[0-9]+\.[0-9]+\.[0-9]+$/
@@ -1913,8 +1920,8 @@ github-release:
     - |
       set -e
       VERSION_TAG="${RELEASE_VERSION:-${CI_COMMIT_TAG:-}}"
-      # Rename agent bundles to include the version for stable releases
-      if [[ "$VERSION_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+      # Rename agent bundles to include the version for all releases (include pre-releases)
+      if [[ "$VERSION_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then
         VERSION="${VERSION_TAG#v}"
         mv dist/assets/agent-bundle_linux_amd64.tar.gz dist/assets/agent-bundle_${VERSION}_linux_amd64.tar.gz
         mv dist/assets/agent-bundle_linux_amd64.tar.gz.asc dist/assets/agent-bundle_${VERSION}_linux_amd64.tar.gz.asc
