[chore] refresh ansible pkg versions

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1976,7 +1976,7 @@ ansible-build:
     paths:
       - dist/
   before_script:
-    - pip3 install ansible==3.4.0
+    - pip3 install 'ansible~=12.0.0'
   script:
     - ansible-galaxy collection build ./deployments/ansible --output-path ./dist
 
@@ -1984,9 +1984,15 @@ ansible-release:
   extends: .ansible
   stage: release
   before_script:
-    - pip3 install ansible==3.4.0 yq==2.12.0
+    - pip3 install 'ansible~=12.0.0 yq~=3.0.0'
   script:
-    - export COLLECTION_VERSION=$(cat ./deployments/ansible/galaxy.yml | yq .version -r)
+    - |
+      COLLECTION_VERSION=$(cat ./deployments/ansible/galaxy.yml | yq .version -r)
+      if [ -z "$COLLECTION_VERSION" ]; then
+        echo "ERROR: Failed to extract version from galaxy.yml" >&2
+        exit 1
+      fi
+      echo "Publishing collection version: $COLLECTION_VERSION"
     - ansible-galaxy collection publish ./dist/signalfx-splunk_otel_collector-${COLLECTION_VERSION}.tar.gz --token=${ANSIBLE_GALAXY_TOKEN}
 
 puppet-release:
