fail job if molecule test fails, but still upload logs

diff --git a/.github/workflows/ansible.yml b/.github/workflows/ansible.yml
--- a/.github/workflows/ansible.yml
+++ b/.github/workflows/ansible.yml
@@ -187,6 +187,7 @@ jobs:
           free -h
 
       - name: Run Molecule tests.
+        id: moleculeTests
         run: |
           mkdir /tmp/log
           molecule --debug -v --base-config ./molecule/config/windows.yml test -s ${{ matrix.scenario }} -p ${{ matrix.distro }}
@@ -201,6 +202,13 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           path: /tmp/log/
+
+      - name: Check if molecule tests passed
+        if: steps.moleculeTests.outcome != 'success'
+        run: |
+            echo "Molecule tests failed for distro: ${{ matrix.distro }} and scenario: ${{ matrix.scenario }}"
+            echo "Check the logs for more details."
+            exit 1
 
   push-release-tag:
     name: Push Release Tag
