Create test matrix for distros

diff --git a/.github/workflows/installer-script-test.yml b/.github/workflows/installer-script-test.yml
--- a/.github/workflows/installer-script-test.yml
+++ b/.github/workflows/installer-script-test.yml
@@ -19,14 +19,35 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  installer-test-matrix:
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v3
+
+      - name: Get distros
+        id: get-matrix
+        run: |
+          # create test matrix for distro images
+          dockerfiles=$(ls internal/buildscripts/packaging/tests/images/deb/Dockerfile.* internal/buildscripts/packaging/tests/images/rpm/Dockerfile.* | cut -d '.' -f2- | sort -u)
+          if [ -z "$dockerfiles" ]; then
+            echo "Failed to get dockerfiles from internal/buildscripts/packaging/tests/images!" >&2
+            exit 1
+          fi
+          distro=$(for d in $dockerfiles; do echo -n "\"$d\","; done)
+          matrix="{\"DISTRO\": [${distro%,}]}"
+          echo "$matrix" | jq
+          echo "matrix=${matrix}" >> $GITHUB_OUTPUT
+    outputs:
+      matrix: ${{ steps.get-matrix.outputs.matrix }}
+
   linux-installer-script-test:
-    name: linux-installer-script-test
     # Use 20.04.5 until https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16450 is resolved
     runs-on: ubuntu-20.04
+    needs: installer-test-matrix
     strategy:
-      matrix:
-        PACKAGE_TYPE: [ "deb", "rpm" ]
-        INSTRUMENTATION: [ "true", "false" ]
+      matrix: ${{ fromJSON(needs.installer-test-matrix.outputs.matrix) }}
+      fail-fast: false
     env:
       PYTHON_VERSION: '3.10'
       PIP_VERSION: '22.0.4'
@@ -57,12 +78,12 @@ jobs:
         timeout-minutes: 45
         run: |
           mkdir -p ${{ env.RESULT_PATH }}
-          if [ "${{ matrix.INSTRUMENTATION }}" = "true" ]; then
-            markers="${{ matrix.PACKAGE_TYPE }} and instrumentation"
-          else
-            markers="${{ matrix.PACKAGE_TYPE }} and not instrumentation"
+          distro="${{ matrix.DISTRO }}"
+          if [[ "$distro" = "amazonlinux-2" ]]; then
+            # workaround for pytest substring matching
+            distro="amazonlinux-2 and not amazonlinux-2023"
           fi
-          pytest -n2 --verbose -m "$markers" \
+          pytest -n auto --verbose -k "$distro" \
             --junitxml=${{ env.RESULT_PATH }}/results.xml \
             --html=${{ env.RESULT_PATH }}/results.html \
             --self-contained-html \
@@ -71,5 +92,5 @@ jobs:
       - name: Uploading artifacts
         uses: actions/upload-artifact@v3
         with:
-          name: linux-installer-script-test-${{ matrix.PACKAGE_TYPE }}-${{ matrix.INSTRUMENTATION }}-result
+          name: linux-installer-script-test-${{ matrix.DISTRO }}-result
           path: ${{ env.RESULT_PATH }}
