Move auto-instr build to a re-usable workflow

diff --git a/.github/workflows/installer-script-test.yml b/.github/workflows/installer-script-test.yml
--- a/.github/workflows/installer-script-test.yml
+++ b/.github/workflows/installer-script-test.yml
@@ -10,8 +10,10 @@ on:
       - '.github/workflows/installer-script-test.yml'
       - '.github/workflows/reusable-compile.yml'
       - '.github/workflows/reusable-build-package.yml'
+      - '.github/workflows/reusable-build-instrumentation-package.yml'
       - 'cmd/otelcol/**'
       - 'internal/**'
+      - 'instrumentation/**'
       - 'packaging/fpm/**'
       - 'packaging/installer/install.sh'
       - 'packaging/tests/instrumentation/**'
@@ -48,6 +50,17 @@ jobs:
       SYS_PACKAGE: ${{ matrix.SYS_PACKAGE }}
       ARCH: ${{ matrix.ARCH }}
 
+  build-instrumentation-package:
+    strategy:
+      matrix:
+        SYS_PACKAGE: [ "deb", "rpm" ]
+        ARCH: [ "amd64", "arm64" ]
+      fail-fast: false
+    uses: ./.github/workflows/reusable-build-instrumentation-package.yml
+    with:
+      SYS_PACKAGE: ${{ matrix.SYS_PACKAGE }}
+      ARCH: ${{ matrix.ARCH }}
+
   installer-test-matrix:
     runs-on: ubuntu-24.04
     steps:
@@ -75,7 +88,7 @@ jobs:
   linux-installer-script-test:
     runs-on: ubuntu-24.04${{ matrix.ARCH == 'arm64' && '-arm' || '' }}
     timeout-minutes: 90
-    needs: [build-package, installer-test-matrix]
+    needs: [build-package, build-instrumentation-package, installer-test-matrix]
     strategy:
       matrix: ${{ fromJSON(needs.installer-test-matrix.outputs.matrix) }}
       fail-fast: false
@@ -112,6 +125,21 @@ jobs:
             exit 1
           fi
           echo "LOCAL_COLLECTOR_PACKAGE=$(realpath "$package_path")" >> "$GITHUB_ENV"
+
+      - name: Download splunk-otel-auto-instrumentation ${{ env.SYS_PACKAGE }} ${{ matrix.ARCH }} package built from source
+        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        with:
+          name: splunk-otel-auto-instrumentation-${{ matrix.ARCH }}-${{ env.SYS_PACKAGE }}
+          path: ./instrumentation-dist
+
+      - name: Set LOCAL_INSTRUMENTATION_PACKAGE
+        run: |
+          package_path=$(find ./instrumentation-dist -maxdepth 1 -name "splunk-otel-auto-instrumentation*.${{ env.SYS_PACKAGE }}" | head -n 1)
+          if [ -z "$package_path" ]; then
+            echo "Failed to find a built splunk-otel-auto-instrumentation .${{ env.SYS_PACKAGE }} package in ./instrumentation-dist!" >&2
+            exit 1
+          fi
+          echo "LOCAL_INSTRUMENTATION_PACKAGE=$(realpath "$package_path")" >> "$GITHUB_ENV"
 
       - name: Setup python
         uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
