[chore] Add Linux smoke test for Collector TA (#6701)
* [chore] Add Linux smoke test for Collector TA

* Setup access_token and wait for launch message

* sudo

* sudo

* Fix the string indicating launch of collector

* Check if alginment fixes actionlint

* Restore alignment add a command

* Try double-quote paths

* Check the collector was not restarted on Linux

* Fix pid commands

* Get all processes

* Fix get otelcol_linux_amd64 PID

* Fix linux ps check and add same to Windows

* Add temporary Get-Process

* On Powershell $pid is a special var user another name

* Double-quote expression

* actionlint

* actionlint

* Collect Windows event log to investigate splunkd restart

* Remove splunk stop

* Use larger Windows runner

* workaround actionlint misidentifying shell on otel-windows

* Stop splunk before installing TA

diff --git a/.github/workflows/splunk-ta-otel.yml b/.github/workflows/splunk-ta-otel.yml
--- a/.github/workflows/splunk-ta-otel.yml
+++ b/.github/workflows/splunk-ta-otel.yml
@@ -161,8 +161,93 @@ jobs:
           name: Splunk_TA_otel
           path: ${{github.workspace}}/build/out/distribution/Splunk_TA_otel.tgz
 
+
+  smoke-test-linux:
+    runs-on: ubuntu-24.04
+    needs: [distribute-ta]
+    steps:
+      - name: Download Collector TA
+        uses: actions/download-artifact@v5
+        with:
+          name: Splunk_TA_otel
+          path: ${{github.workspace}}/build/out/distribution
+
+      - name: Uncompress the Collector TA and prepare local configuration
+        run: |
+          mkdir -p "${{github.workspace}}/build/out/splunk_ta_otel"
+          tar -xzf "${{github.workspace}}/build/out/distribution/Splunk_TA_otel.tgz" -C "${{github.workspace}}/build/out/splunk_ta_otel"
+          cd "${{github.workspace}}/build/out/splunk_ta_otel/Splunk_TA_otel"
+          mkdir local
+          echo "FaKeAcCeSsToKeN" > local/access_token
+
+      - name: Launch Splunk container
+        run: |
+          mkdir -p "${{github.workspace}}/var/log/splunk"
+          docker run -d --name splunk \
+            -e SPLUNK_START_ARGS="--accept-license" -e SPLUNK_PASSWORD="$(uuidgen)" \
+            -v "${{github.workspace}}/build/out/splunk_ta_otel/Splunk_TA_otel":/opt/splunk/etc/apps/Splunk_TA_otel \
+            -v "${{github.workspace}}/var/log/splunk":/opt/splunk/var/log/splunk \
+            "splunk/splunk:${{env.splunk_uf_version}}"
+
+      - name: Wait for Collector launch attempt
+        run: |
+          cd "${{github.workspace}}/var/log/splunk"
+          logFile="Splunk_TA_otel.log"
+          found=false
+          timeout=360
+          elapsed=0
+
+          while [ "$found" = false ] && [ "$elapsed" -lt "$timeout" ]; do
+              if [ -f "$logFile" ]; then
+                  if sudo grep -q "INFO SPLUNK_HOME=/opt/splunk" "$logFile"; then
+                      found=true
+                  fi
+              fi
+              if [ "$found" = false ]; then
+                  sleep 1
+                  elapsed=$((elapsed + 1))
+              fi
+          done
+
+          if [ "$found" = true ]; then
+              echo "Collector was launched after $elapsed seconds"
+          else
+              echo "Timeout reached. Collector was not launched after $elapsed seconds"
+              exit 1
+          fi
+
+      - name: Get otelcol_linux_amd64 PID from Splunk container
+        id: get_pid
+        run: |
+          docker exec splunk sudo ps -aux | grep otelcol_linux_amd64
+          otelcol_pid="$(docker exec splunk sudo ps -aux | grep otelcol_linux_amd64 | awk '{print $2}')"
+          echo "otelcol_linux_amd64 PID $otelcol_pid"
+          echo "otelcol_pid=$otelcol_pid" >> "$GITHUB_OUTPUT"
+
+      - name: Collect log files
+        if: always()
+        run: |
+          cd "${{github.workspace}}/var/log/splunk"
+          ls -l
+          echo -e "\n======= otel.log contents ======="
+          sudo cat otel.log || echo 'otel.log not found'
+          echo -e "\n======= Splunk_TA_otel.log contents ======="
+          sudo cat Splunk_TA_otel.log || echo 'Splunk_TA_otel.log not found'
+          echo -e "\n======= splunkd.log contents ======="
+          sudo cat splunkd.log || echo 'splunkd.log not found'
+
+      - name: Check if otelcol_linux_amd64 process is alive
+        run: |
+          otelcol_pid="${{ steps.get_pid.outputs.otelcol_pid }}"
+          if docker exec splunk sudo ps "$otelcol_pid"; then
+            echo "otelcol_linux_amd64 process ($otelcol_pid) was still running."
+          else
+            echo "otelcol_linux_amd64 process ($otelcol_pid) was not running!"
+            exit 1
+          fi
+
   smoke-test-windows:
-    runs-on: windows-2025
+    runs-on: otel-windows
     needs: [distribute-ta]
     steps:
       - name: Download the Splunk UF MSI
@@ -179,7 +264,14 @@ jobs:
           name: Splunk_TA_otel
           path: ${{github.workspace}}/build/out/distribution
 
-      - name:  Install Splunk_TA_otel on the local Splunk UF
+      - name: Stop Splunk UF
+        # workaround for actionlint not recognizing that "otel-windows" is a windows runner
+        shell: pwsh
+        run: |
+          cd "${Env:ProgramFiles}\SplunkUniversalForwarder\bin"
+          .\splunk.exe stop
+
+      - name: Install Splunk_TA_otel on the local Splunk UF
         run: |
           tar -xzf "${{github.workspace}}/build/out/distribution/Splunk_TA_otel.tgz" -C "${Env:ProgramFiles}\SplunkUniversalForwarder\etc\apps"
           dir "${Env:ProgramFiles}\SplunkUniversalForwarder\etc\apps"
@@ -187,13 +279,17 @@ jobs:
           mkdir local
           Set-Content -Path local/access_token -Value "FaKeAcCeSsToKeN"
 
-      - name: Stop and start Splunk UF
+      - name: Start Splunk UF
+        # workaround for actionlint not recognizing that "otel-windows" is a windows runner
+        shell: pwsh
         run: |
           cd "${Env:ProgramFiles}\SplunkUniversalForwarder\bin"
-          .\splunk.exe stop
+          .\splunk.exe status
           .\splunk.exe start
 
       - name: Wait for Collector launch attempt
+        # workaround for actionlint not recognizing that "otel-windows" is a windows runner
+        shell: pwsh
         run: |
           cd "${Env:ProgramFiles}\SplunkUniversalForwarder\var\log\splunk"
           $logFile = "Splunk_TA_otel.log"
@@ -218,8 +314,32 @@ jobs:
               exit 1
           }
 
-      - name: Log status after test
+      - name: Get otelcol_windows_amd64 PID
+        id: get_pid
+        # workaround for actionlint not recognizing that "otel-windows" is a windows runner
+        shell: pwsh
+        run: |
+          Get-Process
+          $otelcol_pid = (Get-Process -Name otelcol_windows_amd64).Id
+          Write-Host "otelcol_windows_amd64 PID $otelcol_pid"
+          "otelcol_pid=$otelcol_pid" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
+
+      - name: Collect Windows event logs
         if: always()
+        # workaround for actionlint not recognizing that "otel-windows" is a windows runner
+        shell: pwsh
+        run: |
+          Write-Host "Last 50 Application log events:"
+          Get-WinEvent -Log Application -MaxEvents 50 | Format-List TimeCreated, ProviderName, Message
+
+          Write-Host "Last 50 System log events:"
+          Get-WinEvent -Log System -MaxEvents 50 | Format-List TimeCreated, ProviderName, Message
+
+
+      - name: Collect log files
+        if: always()
+        # workaround for actionlint not recognizing that "otel-windows" is a windows runner
+        shell: pwsh
         run: |
           cd "${Env:ProgramFiles}\SplunkUniversalForwarder\var\log\splunk"
           dir
@@ -229,6 +349,19 @@ jobs:
           Get-Content Splunk_TA_otel.log -ErrorAction SilentlyContinue
           Write-Host "`n======= splunkd.log contents ======="
           Get-Content splunkd.log -ErrorAction SilentlyContinue
+
+      - name: Check if otelcol_windows_amd64 process is alive
+        # workaround for actionlint not recognizing that "otel-windows" is a windows runner
+        shell: pwsh
+        run: |
+          $prev_otelcol_pid = ${{ steps.get_pid.outputs.otelcol_pid }}
+          $otelcol_pid = (Get-Process -Id $prev_otelcol_pid).Id
+          if ($otelcol_pid) {
+              Write-Host "otelcol_windows_amd64 process ($prev_otelcol_pid) was still running."
+          } else {
+              Write-Host "otelcol_windows_amd64 process ($prev_otelcol_pid) was not running!"
+              exit 1
+          }
 
   test-discovery:
     name: test-discovery
