sudo

diff --git a/.github/workflows/splunk-ta-otel.yml b/.github/workflows/splunk-ta-otel.yml
--- a/.github/workflows/splunk-ta-otel.yml
+++ b/.github/workflows/splunk-ta-otel.yml
@@ -184,10 +184,10 @@ jobs:
         run: |
           mkdir -p "${{github.workspace}}/var/log/splunk"
           docker run -d --name splunk \
-          -e SPLUNK_START_ARGS="--accept-license" -e SPLUNK_PASSWORD=$(uuidgen) \
-          -v ${{github.workspace}}/build/out/splunk_ta_otel/Splunk_TA_otel:/opt/splunk/etc/apps/Splunk_TA_otel \
-          -v ${{github.workspace}}/var/log/splunk:/opt/splunk/var/log/splunk \
-          splunk/splunk:${{env.splunk_uf_version}}
+            -e SPLUNK_START_ARGS="--accept-license" -e SPLUNK_PASSWORD=$(uuidgen) \
+            -v ${{github.workspace}}/build/out/splunk_ta_otel/Splunk_TA_otel:/opt/splunk/etc/apps/Splunk_TA_otel \
+            -v ${{github.workspace}}/var/log/splunk:/opt/splunk/var/log/splunk \
+            splunk/splunk:${{env.splunk_uf_version}}
 
       - name: Wait for Collector launch attempt
         run: |
@@ -222,11 +222,11 @@ jobs:
           cd "${{github.workspace}}/var/log/splunk"
           ls -l
           echo -e "\n======= otel.log contents ======="
-          cat otel.log || echo 'otel.log not found'
+          sudo cat otel.log || echo 'otel.log not found'
           echo -e "\n======= Splunk_TA_otel.log contents ======="
-          cat Splunk_TA_otel.log || echo 'Splunk_TA_otel.log not found'
+          sudo cat Splunk_TA_otel.log || echo 'Splunk_TA_otel.log not found'
           echo -e "\n======= splunkd.log contents ======="
-          cat splunkd.log || echo 'splunkd.log not found'
+          sudo cat splunkd.log || echo 'splunkd.log not found'
 
   smoke-test-windows:
     runs-on: windows-2025
