Add OSDF file and others to Tanzu artifacts

diff --git a/.github/workflows/tanzu-tile.yml b/.github/workflows/tanzu-tile.yml
--- a/.github/workflows/tanzu-tile.yml
+++ b/.github/workflows/tanzu-tile.yml
@@ -26,7 +26,19 @@ jobs:
     name: Test Tanzu Tile creation
     runs-on: ubuntu-24.04
     steps:
+      - name: Get the Collector version to be packaged
+        run: |
+          COLLECTOR_VERSION=$(wget -qO- --header="Accept: application/json" "https://github.com/signalfx/splunk-otel-collector/releases/latest" | jq -r '.tag_name')
+          if [ -z "$COLLECTOR_VERSION" ]; then
+            echo "Failed to get tag_name for latest release" >&2
+            exit 1
+          fi
+          echo "The Splunk OpenTelemetry Collector version to be packaged is $COLLECTOR_VERSION"
+          echo "COLLECTOR_VERSION=$COLLECTOR_VERSION" >> "$GITHUB_ENV"
+
       - name: Check out the codebase.
+        # Technically it will be more precise for the license check to happen against the label matching the
+        # Collector version, but that makes harder to track updates to scripts and so on.
         uses: actions/checkout@v5
 
       - name: Install license_finder
@@ -43,6 +55,11 @@ jobs:
           cd ../../..
           license_finder --debug
 
+      - name: Generate OSDF file
+        run: |
+          cd ../../..
+          python3 ./deployments/cloudfoundry/tile/scripts/generate_osdf.py --otel-version ${{ env.COLLECTOR_VERSION }}
+
       - name: Set up Homebrew
         id: set-up-homebrew
         uses: Homebrew/actions/setup-homebrew@master
@@ -58,7 +75,8 @@ jobs:
       - name: Run make tile
         shell: bash
         run: |
-          ./make-latest-tile
+          # Ensure that we are targeting the same version as the generated OSDF file.
+          OTEL_VERSION=${{ env.COLLECTOR_VERSION }} ./make-latest-tile
       - name: Check release
         shell: bash
         run: |
@@ -71,10 +89,15 @@ jobs:
           fi
 
           tanzu_tile_path=$(pwd)/"$tanzu_tile_glob"
+          echo "Tanzu Tile glob path $tanzu_tile_path"
           echo "tanzu_tile_path=$tanzu_tile_path" >> "$GITHUB_ENV"
 
       - name: Uploading artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: tanzu-tile-latest.pivotal
-          path: ${{ env.tanzu_tile_path }}
+          name: tanzu-tile-publication-bundle
+          path: |
+            ${{ env.tanzu_tile_path }}
+            deployments/cloudfoundry/bosh/config/blobs.yml
+            deployments/cloudfoundry/tile/resources/latest-release.tgz
+            ../../../OSDF*
