Fix windows image java test (#4762)

diff --git a/.github/workflows/win-package-test.yml b/.github/workflows/win-package-test.yml
--- a/.github/workflows/win-package-test.yml
+++ b/.github/workflows/win-package-test.yml
@@ -532,8 +532,9 @@ jobs:
             exit 1
           }
 
-          $JavaCmdOutput=$(docker exec -it otelcol java -version)
-          if ( ${JavaCmdOutput:0::15} -ne 'openjdk version' ) {
+          docker exec otelcol java -version
+          if ( $LASTEXITCODE -ne 0 ) {
             docker logs otelcol
-            echo "Failing job execution: Failed to run java, command output: ${JavaCmdOutput}"
+            echo "Failing job execution: Failed to run java"
+            exit 1
           }
